spring:
  application:
    name: zroot-user-provider

dubbo:
  registry:
    address: zookeeper://10.11.10.100:2181
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache

zroot:
  user:
    version: 1.0.0